### ISSUE TITLE
Support referencing repos which don't have matching labels

### ISSUE THREAD

**Issue by turt2live** [vector-im/feature-dashboard#38] opened 2019-07-22 17:07 UTC
It's really not great to have a fire label in matrix-doc as it doesn't apply to the project's workflow at all. Labels shouldn't be imposed on projects, the dashboard should adapt to the project.

**Comment by jryans** [comment] 2019-07-22 17:23
Thanks for the feedback! I agree it's not at all ideal. 😭 I think this is a duplicate of https://github.com/vector-im/feature-dashboard/issues/26, so we can use that issue to track a fix.

**Closed by jryans** 2019-07-22 17:23 UTC
